import copy

class Square:

	G = []
	n = 0
	
	def __init__(self, n):
		for i in range(n):
			temp = []
			for k in range(n):
				temp.append(-1)
			self.G.append(temp)
		self.n = n
		self.standardTemplate()

	#make a deep copy of yourself and return it
	def deepCopy(self):
		S = Square(self.n)
		S.G = copy.deepcopy(self.G)
		return S

	#start out a reduced form square
	def standardTemplate(self):
		for i in range(self.n):
			self.G[i][0] = i
			self.G[0][i] = i

	#print to command line
	def printOut(self):
		for i in range(self.n):
			s = ""
			for k in range(self.n):
				if(self.G[i][k] >= 0):
					s += str( self.G[i][k] )
				else:
					s += "X"
				s += " "
			print s

	#The whole matrix is filled (there are no -1 entries)
	def filled(self):
		for i in range(self.n):
			for k in range(self.n):
				if(self.G[i][k] == -1):
					return False
		return True

	#check if you can place s in row r column c
	def canPlace(self, r, c, s):
		if( not (self.rowContains(r, s) or self.colContains(c, s)) ):
			return True
		return False

	#check if row r contains s
	def rowContains(self, r, s):
		for i in range(self.n):
			if(self.G[r][i] == s):
				return True
		return False

	#check if coumn c contains s
	def colContains(self, c, s):
		for i in range(self.n):
			if(self.G[i][c] == s):
				return True
		return False

solved = []	#holds all the solutions generated by the below functions

#find all possible solutions
def solve(LS):
	if(LS.filled()):
		solved.append(LS)
	else:
		for i in range(LS.n):		#rows
			for k in range(LS.n):		#columns
				if(LS.G[i][k] == -1):		#it hasn't been filled			
					for s in range(LS.n):
						if(LS.canPlace(i, k, s)):	#latin square property
							R = LS.deepCopy()
							R.G[i][k] = s		#let's try it then
							solve(R)		#recurse
					return

#stop as soon as you find 1 solution
def solveOne(LS):
	if(LS.filled()):
		solved.append(LS)
		return True
	else:
		for i in range(LS.n):
			for k in range(LS.n):
				if(LS.G[i][k] == -1):
					for s in range(LS.n):
						if(LS.canPlace(i, k, s)):
							R = LS.deepCopy()
							R.G[i][k] = s
							if(solveOne(R)):
								return True
					return False

def main():
	s = Square(5)
	solve(s)
	for i in solved:
		i.printOut()
		print '\n',

	print "the number of squares: " + str(len(solved))

if __name__ == "__main__":
	main()